version: 0.2

phases:
  install:
    runtime-versions:
      golang: latest
  build:
    commands:
      - echo Build started on `date`
      - cd lambda && go build -o bin/app.bin .
  post_build:
    commands:
      - echo Executing create-deployment.sh script
      - ./create-deployment.sh
      - echo Done

artifacts:
  files:
    - '**/*'
