version: '3'

tasks:
  # builds all the lambdas for release to AWS
  build-lambdas:
    dir: 'lambda'
    cmds:
      - go build -o bin/app.bin .
    env:
      GOOS: linux
      GOARCH: amd64

  create-deployment:
    cmds:
      - echo Filename is $filename
    env:
      filename: lambda-bin-{{$RANDOM}}.zip
    silent: true
